### ISSUE TITLE
Unable to require es6_promise_rails

### ISSUE THREAD

**Issue by rardoz** [lbeder/es6-promise-rails#1]
When adding
`require 'es6-promise-rails'`

to the rails asset pipeline, I get an error message of file not found. I figured out a work around, which is using 
`require 'es6/promise/rails'`

rather than what was suggested.

**Comment by lbeder** [comment]
I'm not sure that I follow. 

In a normal setting, you shouldn't require anything at all, but only reference the js script (e.g., by `require promise`) in one of your js files (e.g., `application.js`).

`es6-promise-rails` is indeed a non-existing file, so the message that you got is correct.

**Comment by rardoz** [comment]
I'm trying to automatically require it within my rails engine.

**Comment by lbeder** [comment]
Why do you need to explicitly require it this way? Adding the gem to your Gemfile will place load the gem which in turn will let the pipeline to reference anything in its `vendor/assets` directory, thus referencing `promise.js` from any of your (bundled) js should work like a charm.

It wasn't suggested to require it explicitly, as you've trying to do.

**Comment by rardoz** [comment]
I see what you are saying! In most situations that would be okay, but the gem I'm making requires to have everything to stay contained in my gem. So I am unable to require the js in the main application which uses it. I guess this is a non issue since my circumstance is a little out of the ordinary. I'm still pretty new to rails! Thanks for clearing that up!
